apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: demo
spec:
  containers:
  - name: app1
    image: sakibalamin/app1:1.0.0
    imagePullPolicy: Always
    ports:
    - containerPort: 8001

