apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: demo
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: sakibalamin/app2:1.0.0
    imagePullPolicy: Always
    ports:
    - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8002
    targetPort: 8002
  selector:
    app: app2
